### ISSUE TITLE
启动后无法访问

### ISSUE THREAD

**Issue by taolive** [Mrjeff578575/WebApp-by-Vue2.0-and-MINTUI2.0#1]
npm run dev 命令执行后，访问
http://localhost:8080/ 地址，提示 
Cannot GET /

**Comment by Mrjeff578575** [comment]
看下文件夹下的Index.html是不是丢失了？

**Comment by lgs3137** [comment]
ERROR in ./src/main.js
Module not found: Error: Cannot resolve module 'mint-ui/lib/style.css' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src
 @ ./src/main.js 27:0-32

ERROR in ./src/main.js
Module not found: Error: Cannot resolve module 'mint-ui' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src
 @ ./src/main.js 23:14-32

ERROR in ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/index.vue
Module not found: Error: Cannot resolve module 'mint-ui' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src\components
 @ ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/index.vue 7:14-32

ERROR in ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Cannot resolve module 'mint-ui' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src
 @ ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 9:14-32

ERROR in ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/login.vue
Module not found: Error: Cannot resolve module 'mint-ui' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src\components
 @ ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/login.vue 11:14-32

ERROR in ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/push.vue
Module not found: Error: Cannot resolve module 'mint-ui' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src\components
 @ ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/push.vue 7:14-32

ERROR in ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/test.vue
Module not found: Error: Cannot resolve module 'mint-ui' in D:\nodejs\test\WebApp-by-Vue2.0-and-MINTUI2.0\src\components
 @ ./~/.6.4.1@babel-loader/lib!./~/.9.9.5@vue-loader/lib/selector.js?type=script&index=0!./src/components/test.vue 7:14-32

#################
npm run dev有报错，所以打不开页面~
node v7.7.1

**Comment by Mrjeff578575** [comment]
npm install mint-ui -S

**Comment by lgs3137** [comment]
额，这个为什么不写到dependencies里面去呢？

**Comment by Mrjeff578575** [comment]
Ok,我把这个加进去。

**Comment by lgs3137** [comment]
噗，你改了dependencies的一些依赖版本后webpack又挂了，你clone下来试试看

**Comment by Mrjeff578575** [comment]
这下好了，刚才文件弄错了
