### ISSUE TITLE
你好，能指点一下你打包的过程修改了什么配置吗？我打包的apk无内容显示，拜托了？

### ISSUE THREAD

**Issue by franklin-repo** [Mrjeff578575/WebApp-by-Vue2.0-and-MINTUI2.0#2]
我的修改如下，希望大神能给点意见

1、index.html文件
`<script type="text/javascript" src="cordova.js"></script>`

2、main.js
`window.document.addEventListener('deviceready', function() {
    new Vue({
      router,
      store,
      render: h => h(AppView)
    }).$mount('#app')
    window.navigator.splashscreen.hide()
}, false);`

3、config下的index.js
` assetsSubDirectory: '',
   assetsPublicPath: '',`

**Comment by Mrjeff578575** [comment]
index: path.resolve(__dirname, '../../../cordova/orderApp/www/index.html'),
    assetsRoot: path.resolve(__dirname, '../../../cordova/orderApp/www'),
    assetsSubDirectory: 'static',
    assetsPublicPath: './',
看下这几个路径是否配置正确。

**Comment by franklin-repo** [comment]
你的配置应该是针对在项目里使用cordova 构建一个cordova的项目，然后把npm run build的文件直接导入cordova的打包文件夹www下，我试试你的方案，我在main.js的配置正确吗？

**Comment by Mrjeff578575** [comment]
main.js不用这么写，直接原始那样的就行。
